In [45]:
#IMPORTS
%run ../datuslib.ipynb

In [5]:
#SETTINGS
pd.set_option("display.max_rows", None, "display.max_columns", None)

In [6]:
#CARGA DATA

A_tweets = pd.read_csv(generateAbsolutePath("train.csv", exists = True))

In [49]:
# VER PORQUE MAPEA MAL LOS NOMBRES SI LA INFO LA TIENE

# HACER QUE DEVUELVA EL CONTINENTE EN DONDE DEBE EN VEZ DE DEVOLVER EL PAIS OTRA VEZ 
# (pre hacer mapping entre paises y continentes)

# PORQUE HAY PAISES QUE PONE NADA QUE VER

# HACER QUE USE LOS ACRONIMOS DE PAISES PARA ENCONTRAR PAISES

# PORQUE PONE COMO UNKOWN COSAS QUE SABE

In [46]:
A_tweets2 = A_tweets.copy().head(500)

In [47]:
A_tweets2['parsed location'] = A_tweets2.apply(lambda row : getLocation(row['location']), axis = 1)

In [48]:
A_tweets2[['location','parsed location']]

,location,parsed location
0,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
1,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
2,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
3,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
4,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
5,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
6,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
7,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
8,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
9,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
10,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
11,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
12,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
13,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
14,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
15,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
16,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
17,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
18,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
19,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
20,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
21,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
22,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
23,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
24,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
25,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
26,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
27,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
28,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
29,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
30,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
31,Birmingham,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
32,Est. September 2012 - Bristol,"(Italy, Italy, Este)"
33,AFRICA,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
34,"Philadelphia, PA","(United States, United States, Philadelphia)"
35,"London, UK","(__UNKNOWN, __UNKNOWN, London)"
36,Pretoria,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
37,World Wide!!,"(Italy, Italy, Forlì)"
38,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
39,Paranaque City,"(Brazil, Brazil, Paranaguá)"
40,Live On Webcam,"(Turkey, Turkey, Lice)"
41,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
42,milky way,"(Turkey, Turkey, Milas)"
43,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
44,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
45,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
46,"GREENSBORO,NORTH CAROLINA","(United States, United States, Greensboro)"
47,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
48,Live On Webcam,"(Turkey, Turkey, Lice)"
49,England.,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
50,"Sheffield Township, Ohio","(United Kingdom, United Kingdom, Sheffield)"
51,India,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
52,Barbados,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
53,Anaheim,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
54,Abuja,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
55,USA,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
56,South Africa,"(United Kingdom, United Kingdom, Louth)"
57,"Sao Paulo, Brazil","(Finland, Finland, Salo)"
58,hollywoodland,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
59,"Edmonton, Alberta - Treaty 6","(Canada, Canada, Edmonton)"
60,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
61,Inang Pamantasan,"(Thailand, Thailand, Trang)"
62,Twitter Lockout in progress,"(India, India, Chittūr)"
63,"Concord, CA","(__UNKNOWN, __UNKNOWN, Concord)"
64,"Calgary, AB","(Canada, Canada, Calgary)"
65,Birmingham,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
66,San Francisco,"(Mali, Mali, San)"
67,CLVLND,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
68,"Nashville, TN","(United States, United States, Nashville)"
69,"Santa Clara, CA","(Argentina, Argentina, Salta)"
70,UK,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
71,"St. Louis, MO","(United States, United States, Stow)"
72,"Walker County, Alabama","(United States, United States, Walker)"
73,Australia,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
74,North Carolina,"(Tajikistan, Tajikistan, Norak)"
75,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
76,Norf Carolina,"(Indonesia, Indonesia, Ngoro)"
77,"San Mateo County, CA","(Mali, Mali, San)"
78,North Carolina,"(Tajikistan, Tajikistan, Norak)"
79,"Njoro, Kenya","(Indonesia, Indonesia, Ngoro)"
80,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
81,Your Sister's Bedroom,"(Belgium, Belgium, Dour)"
82,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
83,"Arlington, TX","(__UNKNOWN, __UNKNOWN, Arlington)"
84,"South Bloomfield, OH","(United Kingdom, United Kingdom, Louth)"
85,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
86,"New Hanover County, NC","(Australia, Australia, Kew)"
87,Maldives,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
88,"Manchester, NH","(__UNKNOWN, __UNKNOWN, Manchester)"
89,"Wilmington, NC","(__UNKNOWN, __UNKNOWN, Wilmington)"
90,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
91,"New Hanover County, NC","(Australia, Australia, Kew)"
92,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
93,global,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
94,Alberta | Sask. | Montana,"(Spain, Spain, Almería)"
95,Charlotte,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
96,"Baton Rouge, LA","(Thailand, Thailand, Satun)"
97,"Hagerstown, MD","(United States, United States, Hagerstown)"
98,"Gloucestershire , UK","(Germany, Germany, Westerstede)"
99,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
100,UK,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
101,"Nairobi, Kenya","(Kenya, Kenya, Nairobi)"
102,Instagram - @heyimginog,"(Pakistan, Pakistan, Battagram)"
103,304,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
104,Switzerland,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
105,304,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
106,US,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
107,304,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
108,Instagram - @heyimginog,"(Pakistan, Pakistan, Battagram)"
109,304,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
110,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
111,Somewhere Only We Know ?,"(India, India, Someshwar)"
112,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
113,Belgium,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
114,Switzerland,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
115,US,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
116,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
117,dope show,"(France, France, Dole)"
118,Switzerland,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
119,Switzerland,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
120,"Oshawa, Canada","(Canada, Canada, Oshawa)"
121,Baker City Oregon,"(Senegal, Senegal, Dakar)"
122,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
123,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
124,United States,"(Morocco, Morocco, Fnidek)"
125,304,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
126,304,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
127,marysville ca,"(Benin, Benin, Malanville)"
128,304,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
129,"Hermosa Beach, CA","(Philippines, Philippines, Hermosa)"
130,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
131,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
132,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
133,304,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
134,304,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
135,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
136,"19.600858, -99.047821","(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
137,Pennsylvania,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
138,"Salt Lake City, Utah","(Spain, Spain, Salt)"
139,"Palo Alto, CA","(Philippines, Philippines, Palo)"
140,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
141,"Spain but Opa-Locka, FL","(Thailand, Thailand, Surin)"
142,"Jaipur, India","(India, India, Jaipur)"
143,Hyderabad Telangana INDIA,"(__UNKNOWN, __UNKNOWN, Hyderabad)"
144,"Eagle Pass, Texas","(United States, United States, Eagle)"
145,bangalore,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
146,Financial News and Views,"(Philippines, Philippines, Sitangkai)"
147,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
148,Indonesia,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
149,y(our) boyfriends legs,"(United States, United States, Roy)"
150,"New Mexico, USA","(Australia, Australia, Kew)"
151,Somewhere Out There,"(India, India, Someshwar)"
152,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
153,Mumbai india,"(India, India, Mumbai)"
154,sri lanka,"(Iran, Iran, Sari)"
155,Not a U.S resident,"(Italy, Italy, Noto)"
156,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
157,"Lehigh Valley, PA","(Lesotho, Lesotho, Leribe)"
158,Canada,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
159,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
160,Thrissur,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
161,Havenford,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
162,India,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
163,92,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
164,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
165,Israel,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
166,Fashion Heaven. IG: TMId_,"(Japan, Japan, Mashiko)"
167,"San Francisco, CA","(Mali, Mali, San)"
168,italy,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
169,nyc,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
170,Toronto,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
171,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
172,Jackson,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
173,New York / Worldwide,"(Australia, Australia, Kew)"
174,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
175,"New Orleans, LA","(Australia, Australia, Kew)"
176,West Wales,"(Netherlands, Netherlands, Best)"
177,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
178,Happily Married with 2 kids,"(Japan, Japan, Sapporo)"
179,"Cambridge, MA","(__UNKNOWN, __UNKNOWN, Cambridge)"
180,Arizona,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
181,Mumbai,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
182,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
183,Amsterdam,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
184,"Swindon,England","(United Kingdom, United Kingdom, Swindon)"
185,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
186,Happily Married with 2 kids,"(Japan, Japan, Sapporo)"
187,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
188,"Williamstown, VT","(United States, United States, Williamstown)"
189,"North Carolina, USA","(Tajikistan, Tajikistan, Norak)"
190,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
191,Karachi,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
192,Happily Married with 2 kids,"(Japan, Japan, Sapporo)"
193,Happily Married with 2 kids,"(Japan, Japan, Sapporo)"
194,Loveland Colorado,"(United States, United States, Loveland)"
195,|| c h i c a g o ||,"(India, India, Khada)"
196,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
197,L. A.,"(Chad, Chad, Laï)"
198,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
199,Canada,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
200,VISIT MY YOUTUBE CHANNEL.,"(Sweden, Sweden, Visby)"
201,Lexington,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
202,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
203,USA,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
204,"Hannover, Germany","(Germany, Germany, Hannover)"
205,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
206,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
207,Playa,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
208,"Davidson, NC","(United Kingdom, United Kingdom, Basildon)"
209,Higher Places,"(Liberia, Liberia, Harper)"
210,"Horsemind, MI","(Netherlands, Netherlands, Hoogezand)"
211,"New York, NY","(Australia, Australia, Kew)"
212,Boksburg,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
213,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
214,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
215,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
216,"V-RP @OZRP_ ?MV, AU, R18+?","(Turkey, Turkey, Van)"
217,"Greater Manchester, UK","(Ghana, Ghana, Prestea)"
218,Boston,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
219,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
220,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
221,The Canopy Kingdom,"(China, China, Tahe)"
222,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
223,USA,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
224,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
225,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
226,the own zone layer,"(China, China, Tahe)"
227,London,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
228,Trancy Manor,"(France, France, Drancy)"
229,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
230,South 37,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
231,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
232,"West Lancashire, UK.","(Netherlands, Netherlands, Best)"
233,PA,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
234,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
235,Û¢ Views From The Six Û¢,"(India, India, Khada)"
236,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
237,University of Toronto,"(United States, United States, University)"
238,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
239,Swaning Around,"(China, China, Suining)"
240,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
241,London,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
242,Albany/NY,"(__UNKNOWN, __UNKNOWN, Albany)"
243,"California, USA","(__UNKNOWN, __UNKNOWN, California)"
244,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
245,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
246,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
247,Wild Wild Web,"(United States, United States, Hilo)"
248,Subconscious LA,"(Canada, Canada, Beaconsfield)"
249,Spain,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
250,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
251,CA physically- Boston Strong?,"(Venezuela, Venezuela, Cúa)"
252,"Yeezy Taught Me , NV","(Chad, Chad, Benoy)"
253,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
254,CA physically- Boston Strong?,"(Venezuela, Venezuela, Cúa)"
255,United States,"(Morocco, Morocco, Fnidek)"
256,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
257,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
258,"Rock Hill, SC","(Djibouti, Djibouti, Obock)"
259,"Coolidge, AZ","(United Kingdom, United Kingdom, Aldridge)"
260,Republic of Texas,"(United States, United States, Republic)"
261,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
262,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
263,"Phoenix, AZ","(United States, United States, Phoenix)"
264,"Ljubljana, Slovenia","(Slovenia, Slovenia, Ljubljana)"
265,Connecticut,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
266,"Tacoma,Washington","(United States, United States, Tacoma)"
267,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
268,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
269,Subconscious LA,"(Canada, Canada, Beaconsfield)"
270,BIG D HOUSTON/BOSTON/DENVER,"(Turkey, Turkey, Biga)"
271,"Chandler, AZ","(United States, United States, Chandler)"
272,ColoRADo,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
273,sindria,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
274,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
275,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
276,Texas,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
277,"Elk Grove, CA, USA","(United States, United States, Elko)"
278,Texas,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
279,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
280,The Shire,"(China, China, Tahe)"
281,"Austin, TX","(__UNKNOWN, __UNKNOWN, Austin)"
282,Oakland,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
283,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
284,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
285,Albuquerque,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
286,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
287,"Buenos Aires, Argentina","(__UNKNOWN, __UNKNOWN, Burgos)"
288,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
289,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
290,"San Antonio-ish, TX","(Mali, Mali, San)"
291,San Francisco,"(Mali, Mali, San)"
292,"Oregon, USA","(United States, United States, Oregon)"
293,"Harlingen, TX","(__UNKNOWN, __UNKNOWN, Harlingen)"
294,Buffalo NY,"(__UNKNOWN, __UNKNOWN, Buffalo)"
295,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
296,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
297,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
298,Las Vegas,"(Chad, Chad, Laï)"
299,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
300,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
301,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
302,Tokyo,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
303,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
304,"California, United States","(__UNKNOWN, __UNKNOWN, California)"
305,"California, United States","(__UNKNOWN, __UNKNOWN, California)"
306,#FLIGHTCITY UK,"(__UNKNOWN, __UNKNOWN, Florencia)"
307,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
308,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
309,"Alphen aan den Rijn, Holland","(Germany, Germany, Aachen)"
310,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
311,Wrigley Field,"(__UNKNOWN, __UNKNOWN, Shirley)"
312,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
313,probably the strip club,"(Cyprus, Cyprus, Protaras)"
314,Canada,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
315,England,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
316,USA,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
317,"California, United States","(__UNKNOWN, __UNKNOWN, California)"
318,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
319,"California, United States","(__UNKNOWN, __UNKNOWN, California)"
320,New York City,"(Australia, Australia, Kew)"
321,Here And There,"(China, China, Heze)"
322,"Rotterdam, Zuid-Holland","(__UNKNOWN, __UNKNOWN, Rotterdam)"
323,"Derry, 17","(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
324,Nowhere. Everywhere.,"(Japan, Japan, Noshiro)"
325,"Florida, USA","(__UNKNOWN, __UNKNOWN, Florida)"
326,Worldwide,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
327,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
328,Nowhere. Everywhere.,"(Japan, Japan, Noshiro)"
329,East Coast,"(Netherlands, Netherlands, Elst)"
330,California,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
331,"Toronto, ON","(Canada, Canada, Toronto)"
332,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
333,The Orwellion police-state,"(China, China, Tahe)"
334,"Castaic, CA","(United States, United States, Castaic)"
335,"Helsinki, Finland","(Finland, Finland, Helsinki)"
336,East Kilbride,"(Netherlands, Netherlands, Elst)"
337,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
338,#FLIGHTCITY UK,"(__UNKNOWN, __UNKNOWN, Florencia)"
339,middle eastern palace,"(Morocco, Morocco, Midelt)"
340,Kent,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
341,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
342,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
343,Nowhere. Everywhere.,"(Japan, Japan, Noshiro)"
344,#FLIGHTCITY UK,"(__UNKNOWN, __UNKNOWN, Florencia)"
345,Perthshire,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
346,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
347,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
348,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
349,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
350,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
351,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
352,twitch.tv/naturalemblem26,"(Mexico, Mexico, Toluca)"
353,cyprus,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
354,"Memphis, TN","(United States, United States, Memphis)"
355,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
356,Studio,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
357,"Hollywood, CA","(__UNKNOWN, __UNKNOWN, Hollywood)"
358,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
359,New York,"(Australia, Australia, Kew)"
360,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
361,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
362,Pakistan,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
363,Mexico! ^_^,"(Philippines, Philippines, Mexico)"
364,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
365,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
366,Campinas Sp,"(__UNKNOWN, __UNKNOWN, Campinas)"
367,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
368,"Harlem, New York","(United States, United States, Harlem)"
369,New York,"(Australia, Australia, Kew)"
370,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
371,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
372,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
373,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
374,"Washington, DC","(__UNKNOWN, __UNKNOWN, Washington)"
375,"Burbank,CA","(__UNKNOWN, __UNKNOWN, Burbank)"
376,New York,"(Australia, Australia, Kew)"
377,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
378,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
379,?,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
380,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
381,"Spokane, Washington","(United States, United States, Spokane)"
382,USA,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
383,"Charlotte, NC","(United States, United States, Charlotte)"
384,Our Empire State,"(Belgium, Belgium, Dour)"
385,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
386,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
387,Jerusalem,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
388,"Kingston, Pennsylvania","(__UNKNOWN, __UNKNOWN, Kingston)"
389,"Milwaukee, WI","(United States, United States, Milwaukee)"
390,Zero Branco,"(Japan, Japan, Gero)"
391,Republic of Texas,"(United States, United States, Republic)"
392,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
393,bajaur,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
394,USA,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
395,"Eldoret, kenya","(Kenya, Kenya, Eldoret)"
396,ÛÊÛÊÛÊ,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
397,Jerusalem,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
398,"Miami,FL","(United States, United States, Miami)"
399,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
400,"Los Angeles, CA","(France, France, Loos)"
401,"North-East Region, Singapore","(Tajikistan, Tajikistan, Norak)"
402,"Eldoret, kenya","(Kenya, Kenya, Eldoret)"
403,NaN,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
404,Chicago,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
405,EARTH,"(__UNKNOWN, __UNKNOWN, __UNKNOWN)"
406,"Jerusalem, Israel","(Israel, Israel, Jerusalem)"